#
# Module manifest for module 'RC4ADCheck'
#
# Generated by: Jan Tiedemann
#
# Generated on: 3/27/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'RC4ADCheck.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'b8e7c5a2-3f1d-4e6b-9a0c-2d5f8e1b4c7a'

# Author of this module
Author = 'Jan Tiedemann'

# Company or vendor of this module
CompanyName = 'Community'

# Copyright statement for this module
Copyright = '(c) Jan Tiedemann. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell toolkit for assessing DES and RC4 Kerberos encryption usage in Active Directory. Discovers RC4/DES dependencies across DC encryption, trusts, KRBTGT, service accounts, KDC registry, KDCSVC events, and Security event logs — with inline remediation commands and assessment comparison for tracking progress toward the July 2026 RC4 removal deadline.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-AccountEncryptionAssessment', 'Get-AuditPolicyCheck', 
               'Get-ChangeIndicator', 'Get-DomainControllerEncryption', 
               'Get-EventLogEncryptionAnalysis', 'Get-GuidancePlainText', 
               'Get-KdcRegistryAssessment', 'Get-KdcSvcEventAssessment', 
               'Get-TrustEncryptionAssessment', 'Invoke-DomainAssessment', 
               'Show-AssessmentSummary', 'Show-ForestSummary', 
               'Show-ManualValidationGuidance'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        Tags = @('ActiveDirectory', 'Kerberos', 'RC4', 'DES', 'AES', 'Encryption', 'Security', 'Assessment', 'Remediation')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/BetaHydri/RC4_AD_Check/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/BetaHydri/RC4_AD_Check'

        # A URL to an icon representing this module.
        # IconUri = ''

        ReleaseNotes = ''

        Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}



